# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0002_add_timetable_journey_and_calling_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablejourney',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='callingpoint',
            name='calling_point_type',
            field=models.CharField(choices=[('OR', 'Passenger Origin'), ('OPOR', 'Operational Origin'), ('IP', 'Passenger Intermediate'), ('OPIP', 'Operational Intermediate'), ('PP', 'Intermediate Passing Point'), ('DT', 'Passenger Destination'), ('OPDT', 'Operational Destination')], max_length=2),
        ),
    ]
