# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0003_auto_20160401_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('timetabled_calling_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='darwinpushport.CallingPoint')),
            ],
        ),
        migrations.AlterField(
            model_name='operatingcompany',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
