# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0004_auto_20160401_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('import_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
