# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def delete_objects_with_null_times_or_datetimes(apps, schema_editor):
    ActualArrival = apps.get_model('darwinpushport', 'ActualArrival')

    ActualArrival.objects.filter(
        Q(time__isnull=True) |
        Q(datetime__isnull=True)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0006_add_datetime_fields'),
    ]

    operations = [
        migrations.RunPython(
            delete_objects_with_null_times_or_datetimes),

        migrations.AlterField(
            model_name='actualarrival',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
