# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0007_make_times_datetimes_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyFromTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='darwinpushport.Location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='darwinpushport.Location')),
                ('journeys', models.ManyToManyField(related_name='_journeyfromto_journeys_+', to='darwinpushport.TimetableJourney')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='journeyfromto',
            unique_together=set([('from_location', 'to_location')]),
        ),
        migrations.AlterIndexTogether(
            name='journeyfromto',
            index_together=set([('from_location', 'to_location')]),
        ),
    ]
