# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0008_add_journey_from_to_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablejourney',
            name='late_reason',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
