# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0010_add_late_reason_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LateRunningReason',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
