# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0011_add_cancellation_and_late_running_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualarrival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callingpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetablejourney',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
