# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0012_add_created_at_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='callingpoint',
            name='public_visible',
            field=models.BooleanField(default=True),
        ),
    ]
