# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0013_add_public_visible_to_calling_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callingpoint',
            name='calling_point_type',
            field=models.CharField(choices=[('OR', 'Passenger Origin'), ('OPOR', 'Operational Origin'), ('IP', 'Passenger Intermediate'), ('OPIP', 'Operational Intermediate'), ('PP', 'Intermediate Passing Point'), ('DT', 'Passenger Destination'), ('OPDT', 'Operational Destination')], max_length=4),
        ),
    ]
