# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darwinpushport', '0014_increase_length_of_calling_point_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPassengerJourney',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtti_train_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='callingpoint',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='actualarrival',
            name='timetabled_calling_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual_arrival', to='darwinpushport.CallingPoint'),
        ),
        migrations.AlterField(
            model_name='callingpoint',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_calling_points', to='darwinpushport.TimetableJourney'),
        ),
    ]
