# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_code', models.CharField(db_index=True, max_length=2)),
                ('atoc_code', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(db_index=True, max_length=256)),
            ],
        ),
    ]
