# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuslocation',
            name='uic_code',
            field=models.CharField(blank=True, db_index=True, help_text='International Union of Railways (Union Internationale des Chemins de fer) code.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corpuslocation',
            name='national_location_code',
            field=models.CharField(blank=True, db_index=True, help_text='(NLC) - A 6-digit code. These includes physical locations such as stations and junctions as well as codes relating to accounting and other purposes.', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='corpuslocation',
            name='nlc_description',
            field=models.CharField(blank=True, db_index=True, help_text='Description of the national location code (NLC)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='corpuslocation',
            name='nlc_short_description',
            field=models.CharField(blank=True, db_index=True, help_text='(Supposedly) 16-char description of the national location code (NLC)', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='corpuslocation',
            name='tiploc',
            field=models.CharField(blank=True, db_index=True, help_text='Timing Point Location - Codes relating to points used in deriving train schedules', max_length=50, null=True),
        ),
    ]
