# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpus', '0002_auto_20160321_0905'),
        ('naptan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusNaptanLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_warning', models.CharField(blank=True, max_length=100, null=True)),
                ('corpus_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corpus.CorpusLocation')),
                ('naptan_rail_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='naptan.NaptanRailStation')),
            ],
        ),
    ]
